### ISSUE TITLE
500 Error on api/ping or when sending tasks to the central scheduler

### ISSUE THREAD

**Issue by mbelmadani** [spotify/luigi#1661]
I'm trying to launch tasks using the central scheduler. If I do the local-scheduler version, it works fine:

```
(venv) mbelmadani@pavdesk-27:~/development/paperpipe/pipeline$ PYTHONPATH='' luigi --module main CountLetters --local-scheduler
DEBUG: Checking if CountLetters() is complete
INFO: Informed scheduler that task   CountLetters__99914b932b   has status   DONE
INFO: Done scheduling tasks
INFO: Running Worker with 1 processes
DEBUG: Asking scheduler for work...
DEBUG: Done
DEBUG: There are no more tasks to run at this time
INFO: Worker Worker(salt=662898061, workers=1, host=pavdesk-27, username=mbelmadani, pid=9166) was stopped. Shutting down Keep-Alive thread
INFO: 
===== Luigi Execution Summary =====

Scheduled 1 tasks of which:
* 1 present dependencies were encountered:
    - 1 CountLetters()

Did not run any tasks
This progress looks :) because there were no failed tasks or missing external dependencies

===== Luigi Execution Summary =====
```

But the central scheduler version gives me this error.

```
(venv) mbelmadani@pavdesk-27:~/development/paperpipe/pipeline$ PYTHONPATH='' luigi --module main CountLetters 
DEBUG: Checking if CountLetters() is complete
ERROR: Failed connecting to remote scheduler 'http://localhost:8082'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/luigi-2.1.1-py2.7.egg/luigi/rpc.py", line 127, in _fetch
    response = self._fetcher.fetch(full_url, body, self._connect_timeout)
  File "/usr/local/lib/python2.7/dist-packages/luigi-2.1.1-py2.7.egg/luigi/rpc.py", line 88, in fetch
    resp.raise_for_status()
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 773, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 500 Server Error: Internal Server Error
INFO: Retrying...

```
But the web application for the central scheduler works fine on http://localhost:8082/ for the looks of it. However, if I access (through the browser) the api/ping endpoint, I get an uncaught exception:

```
2016-04-20 13:23:45,457 tornado.application[8990] ERROR: Uncaught exception GET /api/ping (::1)
HTTPRequest(protocol='http', host='localhost:8082', method='GET', uri='/api/ping', version='HTTP/1.1', remote_ip='::1', headers={'Accept-Language': 'en-US,en;q=0.8,fr;q=0.6', 'Accept-Encoding': 'gzip, deflate, sdch', 'Host': 'localhost:8082', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/49.0.2623.108 Chrome/49.0.2623.108 Safari/537.36', 'Dnt': '1', 'Connection': 'keep-alive', 'Cache-Control': 'max-age=0', 'Upgrade-Insecure-Requests': '1'})
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/tornado/web.py", line 1141, in _when_complete
    callback()
  File "/usr/lib/python2.7/dist-packages/tornado/web.py", line 1162, in _execute_method
    self._when_complete(method(*self.path_args, **self.path_kwargs),
  File "/usr/local/lib/python2.7/dist-packages/luigi-2.1.1-py2.7.egg/luigi/server.py", line 101, in get
    result = getattr(self._scheduler, method)(**arguments)
  File "/usr/local/lib/python2.7/dist-packages/luigi-2.1.1-py2.7.egg/luigi/scheduler.py", line 822, in ping
    worker_id = kwargs['worker']
KeyError: 'worker'
```

Any suggestions on how to debug this?

**Comment by dlstadther** [comment]
Potentially dumb question... did you execute `sudo luigid --backgroun` prior to this?

**Comment by mbelmadani** [comment]
I did run luigid in the background, but not as sudo. I just tried it and the server still returns 500 errors.

Here is my server launch command:
```
#!/bin/bash
luigid --background --pidfile PIDFILE --logdir logs/ --state-path STATE
```

**Comment by Tarrasch** [comment]
> However, if I access (through the browser) the api/ping endpoint, I get an uncaught exception

Yea that's expected. You must say what worker is pinging (and hence shouldn't be pruned). Right?

---

To debug this: What does the server spit out when you get the error on the client side? By the way, make sure to have a recent version (>= 2.1.0) of the server.

**Comment by mbelmadani** [comment]
The server output is:

>2016-04-21 12:21:11,933 tornado.access[17291] ERROR: 500 GET /api/ping (127.0.0.1) 0.47ms
2016-04-21 12:21:12,935 tornado.application[17291] ERROR: Uncaught exception GET /api/ping (127.0.0.1)

>HTTPRequest(protocol='http', host='localhost:8082', method='GET', uri='/api/ping', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Content-Length': '137', 'Accept-Encoding': 'gzip, deflate, compress', 'Content-Type': 'application/x-www-form-urlencoded', 'Host': 'localhost:8082', 'Accept': '*/*', 'User-Agent': 'python-requests/2.2.1 CPython/2.7.6 Linux/3.16.0-62-generic'})
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/tornado/web.py", line 1141, in _when_complete
    callback()
  File "/usr/lib/python2.7/dist-packages/tornado/web.py", line 1162, in _execute_method
    self._when_complete(method(*self.path_args, **self.path_kwargs),
  File "/usr/local/lib/python2.7/dist-packages/luigi-2.1.1-py2.7.egg/luigi/server.py", line 101, in get
    result = getattr(self._scheduler, method)(**arguments)
  File "/usr/local/lib/python2.7/dist-packages/luigi-2.1.1-py2.7.egg/luigi/scheduler.py", line 822, in ping
    worker_id = kwargs['worker']
KeyError: 'worker'
2016-04-21 12:21:12,935 tornado.access[17291] ERROR: 500 GET /api/ping (127.0.0.1) 0.45ms

I cloned the repo yesterday, so it should be more recent than 2.1

**Comment by Tarrasch** [comment]
Maybe you run into the issue that's fixed by https://github.com/spotify/luigi/pull/1395. Though if you cloned instead of pip-installed, you might run with an old (<4.0) version of tornado. Let me know what you can find. :)

**Comment by mbelmadani** [comment]
I got it working. Turns out I also had luigi  installed system-wide (not in my project's virtualenv) and that would cause the issue when running luigid inside or outside the virtualenv. I removed them, created a new environment, pip installed from the environnement and now everything works just fine.

Thanks!

**Comment by elipapa** [comment]
I still have this issue even with tornado >4 and < 5.
The luigi-server logs are:

```sh
2017-12-07 10:21:50,970 tornado.access[5263] INFO: 200 GET /api/task_list?data=%7B%22status%22%3A%22DONE%22%2C%22upstream_status%22%3A%22%22%2C%22search%22%3A%22%22%7D (::1) 0.37ms
2017-12-07 10:25:10,587 tornado.application[5263] ERROR: Uncaught exception GET /api/ping (::1)
HTTPServerRequest(protocol='http', host='localhost:8082', method='GET', uri='/api/ping', version='HTTP/1.1', remote_ip='::1', headers={'Accept-Encoding': 'gzip, deflate', 'Host': 'localhost:8082', 'Connection': 'keep-alive', 'Accept': '*/*', 'User-Agent': 'HTTPie/0.9.8'})
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1467, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/src/luigi/luigi/server.py", line 77, in get
    result = getattr(self._scheduler, method)(**arguments)
  File "/src/luigi/luigi/scheduler.py", line 1181, in ping
    worker_id = kwargs['worker']
KeyError: 'worker'
```

any other suggestion?

**Comment by vpv-csc** [comment]
We saw the same issue as @elipapa and had troubleshooting it took a while. I'll document the fix here, in case someone finds it with Google or something.

We're using CentOS 7. At some point the python-tornado package in CentOS 7 was updated from python-tornado-2.2.1-8.el7.noarch to python-tornado-4.2.1-1.el7.x86_64. It should be noted that the package changed architecture from noarch to x86_64 at the same time.

The packaging has a bug of some sort, which causes the system to have leftover tornado code in /usr/lib/python2.7/site-packages/tornado even though the current code installed by the x86_64 package is in /usr/lib64/python2.7/site-packages/tornado. Python seems to prefer the outdated noarch code to the current x86_64 code.

The fix is to remove the directory /usr/lib/python2.7/site-packages/tornado and its contents manually.

**Comment by H4dr1en** [comment]
I also had this error while trying to access to `/api/ping` and I was not able to start a task.
After upgrading `tornado` to `6.0.3`, starting a task worked, even though accessing to `/api/ping` still returns the same error.

**Comment by naicigam** [comment]
I was able to reproduce this error from version 2.6.0.
Version 2.5.0 works for me.

**Comment by tashrifbillah** [comment]
@H4dr1en , do you recall how you pinged your worker? It should be something like:

```js
http://localhost:8082/api/ping?data={"worker":"name_of_worker"}
```

as found [here](https://github.com/spotify/luigi/blob/cf4b6fbcd88a4ad93a76435a0d74c691303169c4/test/server_test.py#L333).

Yet, my problem is I am not sure what my worker name is. I have the following console output. Can you guess?

```bash
INFO: Running Worker with 1 processes
INFO: [pid 57799] Worker Worker(salt=934948318, workers=1, host=localhost, username=571, pid=57799) running   TaskA(a=0.236)
INFO: [pid 57799] Worker Worker(salt=934948318, workers=1, host=localhost, username=571, pid=57799) done      TaskA(a=0.236)
INFO: Informed scheduler that task   TaskA_0_236_19ec3786da   has status   DONE
INFO: [pid 57799] Worker Worker(salt=934948318, workers=1, host=localhost, username=571, pid=57799) running   TaskB(a=0.236, b=0.274)
INFO: [pid 57799] Worker Worker(salt=934948318, workers=1, host=localhost, username=571, pid=57799) done      TaskB(a=0.236, b=0.274)


```
